### ISSUE TITLE
Execution failed for task ':installDeviceDebug'. > java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by jaredsburrows** [novoda/gradle-android-command-plugin#138]
## Description:
Even though it fails on `installDeviceDebug`, it still installs but does not do the `runDebug`.

## Repo:
`$ gradlew assembleDebug installDebug runDebug -s`

## Version:
`2.0`

## Error:
```
> Task :installDebug 
Installing APK 'android-gif-example-debug.apk' on 'Pixel - 8.1.0' for android-gif-example:debug
Installed on 1 device.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installDeviceDebug'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':installDeviceDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:623)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:578)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NullPointerException
        at com.novoda.gradle.command.AdbCommand.execute(AdbCommand.groovy:10)
        at com.novoda.gradle.command.AdbCommand$execute.call(Unknown Source)
        at com.novoda.gradle.command.AdbTask.assertDeviceConnected(AdbTask.groovy:46)
        at com.novoda.gradle.command.AdbTask.assertDeviceAndRunCommand(AdbTask.groovy:39)
        at com.novoda.gradle.command.Install.exec(Install.groovy:34)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 31 more


* Get more help at https://help.gradle.org

BUILD FAILED in 9s
35 actionable tasks: 5 executed, 30 up-to-date
```

**Comment by tasomaniac** [comment]
Thank you for the detailed report. Version 2.0 didn't change a lot regarding this. The `NullPointerException` seems to be almost impossible in the given line.

You shouldn't do `assemble`, `install` and `run` together. Especially if you have parallel builds enabled, that would be a problem. `install` and `installDevice` are different. `install` is coming from Android plugin and installs on all devices. `installDevice` installs on a given device. First one by default, can be overridden with `-PdeviceId=`

Can you try following things:

- Can you share your gradle and Android plugin version with us?
- Try with just `./gradlew runDebug`. This will assemble and install for you. 
- You can also do `startDebug` after a regular Android `installDebug` task. This will just `start` rather than install and start which is useful if you need to run `install` task yourself. 
- If you have parallel enabled, can you try with `--no-parallel` command line argument?

**Comment by jaredsburrows** [comment]
Before upgrading to `2.0`, I always used `gradlew assembleDebug installDebug runDebug`. 

> Can you share your gradle and Android plugin version with us?

https://github.com/jaredsburrows/android-gif-example

> If you have parallel enabled, can you try with --no-parallel command line argument?

The build is not parallel. JavaCompile forking option is set to true but this should not effect anything. https://github.com/jaredsburrows/android-gif-example/blob/master/gradle/compile.gradle.kts#L18

With running just `gradlew runDebug`:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installDeviceDebug'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 58s
33 actionable tasks: 33 executed
```

**Comment by tasomaniac** [comment]
Thanks for getting back quick. I think for now you can do `./gradlew installDebug startDebug`
And I will try to reproduce this to see what's wrong.

**Comment by jaredsburrows** [comment]
@tasomaniac 
`startDebug` does not work as well:
```
$ gradlew startDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':startDebug'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```

**Comment by jaredsburrows** [comment]
Any update on this? Maybe possible revert?

**Comment by devisnik** [comment]
Sorry for the delay, we'll try to look into this asap. For now, just stick to version `1.7.1`.
