### ISSUE TITLE
Monkey output is not being propagated to gradle

### ISSUE THREAD

**Issue by ouchadam** [novoda/gradle-android-command-plugin#63]
The gradle output isn't too helpful!

```
Caused by: groovy.lang.GroovyRuntimeException: Monkey run failed
	at com.novoda.gradle.command.Monkey.handleCommandOutput(Monkey.groovy:12)
	at com.novoda.gradle.command.AdbTask.runCommand(AdbTask.groovy:48)
	at com.novoda.gradle.command.AdbTask.assertDeviceAndRunCommand(AdbTask.groovy:42)
	at com.novoda.gradle.command.Monkey.exec(Monkey.groovy:17)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 47 more
```

**Comment by devisnik** [comment]
Could you please specify your gradle call. Did you try using `--info`?

**Comment by ouchadam** [comment]
`monkeyFlavorDebug`

and using `--info` outputs the same log

**Comment by devisnik** [comment]
Using `--debug` you get the actual monkey output. 

We might consider making this more accessible though. Ideas?

**Comment by ouchadam** [comment]
still no monkey output with `--debug`

**Comment by ouchadam** [comment]
This was user error, the `--info` and `--debug` do both get the monkey output.

**Comment by blundell** [comment]
:+1: we need them on the ci then right :D --info

**Comment by blundell** [comment]
(i came here for the same thing haha)
